In [1]:
import numpy as np

# Partie 1: Listes Python vs Tableaux NumPy

In [10]:
# 1) Liste Python
temperatures_liste=[24.5, 25.1, 26.3, 27.0, 25.8]

# 2) Tableau NumPy équivalent
temperatures_np=np.array(temperatures_liste)

# 3) Multiplication par 2
resultat_liste=temperatures_liste * 2  # duplique la liste
resultat_np=temperatures_np * 2        # multiplie chaque valeur

print("Liste x2 : ", resultat_liste)
print("NumPy x2 : ", resultat_np)

  # 4) Différence observée : 
  #    - Sur une liste Python, `* 2` duplique la liste (concaténation). 
  #    - Sur un tableau NumPy, `* 2` multiplie chaque élément (opération vectorisée, élément par élément).

Liste x2 :  [24.5, 25.1, 26.3, 27.0, 25.8, 24.5, 25.1, 26.3, 27.0, 25.8]
NumPy x2 :  [49.  50.2 52.6 54.  51.6]


# Partie 2 : Création des données

In [11]:
# 1) 10 mesures de température initialisées à zéro
temp_zeros=np.zeros(10)

# 2) 10 valeurs égales à 1
temp_ones=np.ones(10)

# 3) 10 valeurs initialisées à 25
temp_25=np.full(10, 25)

# 4) Matrice identité 5x5
identite=np.eye(5)

# 5) Les 24 heures d'une journée (0 à 23)
heures=np.arange(24)

# 6) 10 valeurs régulièrement réparties entre 20°C et 30°C
temp_reparties=np.linspace(20, 30, 10)

# 7) 100 températures aléatoires reproductibles
rng=np.random.default_rng(seed=42)
temp_aleatoires=rng.normal(loc=25, scale=3, size=100).round(1)

print("Zéros : ", temp_zeros)
print("Uns : ", temp_ones)
print("25 :", temp_25)
print("Identité :\n", identite)
print("Heures :", heures)
print("Réparties 20-30 :", temp_reparties)
print("Aléatoires (extrait) :", temp_aleatoires[:10])

Zéros :  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Uns :  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
25 : [25 25 25 25 25 25 25 25 25 25]
Identité :
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Heures : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Réparties 20-30 : [20.         21.11111111 22.22222222 23.33333333 24.44444444 25.55555556
 26.66666667 27.77777778 28.88888889 30.        ]
Aléatoires (extrait) : [25.9 21.9 27.3 27.8 19.1 21.1 25.4 24.1 24.9 22.4]


# Partie 3 : Exploration des tableaux

In [12]:
# 1) 24 températures aléatoires d'une journée
rng=np.random.default_rng(seed=1)
temperatures_jour=rng.normal(loc=25, scale=3, size=24).round(1)

print("Températures: ", temperatures_jour)

# 2) Propriétés du tableau
print("a) Nombre de dimensions :", temperatures_jour.ndim)
print("b) Nombre de valeurs :", temperatures_jour.size)
print("c) Type des données :", temperatures_jour.dtype)
print("d) Forme du tableau :", temperatures_jour.shape)


Températures:  [26.  27.5 26.  21.1 27.7 26.3 23.4 26.7 26.1 25.9 25.1 26.6 22.8 24.5
 23.6 26.8 25.1 24.1 22.7 24.2 25.  24.2 28.9 28. ]
a) Nombre de dimensions : 1
b) Nombre de valeurs : 24
c) Type des données : float64
d) Forme du tableau : (24,)


# Partie 4 : Indexation et slicing

In [13]:
# 1) Première mesure
print("Première mesure :", temperatures_jour[0])

# 2) Dernière mesure
print("Dernière température :", temperatures_jour[-1])

# 3) Température de 8h
print("Température à 8h :", temperatures_jour[8])

# 4) Températures de 8h à 12h
print("Températures 8h-12h :", temperatures_jour[8:13])

# 5) Températures des 6 premières heures
print("6 premières heures :", temperatures_jour[:6])

# 6) Températures des heures paires
print("Heures paires :", temperatures_jour[::2])

Première mesure : 26.0
Dernière température : 28.0
Température à 8h : 26.1
Températures 8h-12h : [26.1 25.9 25.1 26.6 22.8]
6 premières heures : [26.  27.5 26.  21.1 27.7 26.3]
Heures paires : [26.  26.  27.7 23.4 26.1 25.1 22.8 23.6 25.1 22.7 25.  28.9]
