In [5]:
import numpy as np

# Partie 1: Listes Python vs Tableaux NumPy

In [6]:
# 1) Liste Python
temperatures_liste=[24.5, 25.1, 26.3, 27.0, 25.8]

# 2) Tableau NumPy équivalent
temperatures_np=np.array(temperatures_liste)

# 3) Multiplication par 2
resultat_liste=temperatures_liste * 2  # duplique la liste
resultat_np=temperatures_np * 2        # multiplie chaque valeur

print("Liste x2 : ", resultat_liste)
print("NumPy x2 : ", resultat_np)

  # 4) Différence observée : 
  #    - Sur une liste Python, `* 2` duplique la liste (concaténation). 
  #    - Sur un tableau NumPy, `* 2` multiplie chaque élément (opération vectorisée, élément par élément).

Liste x2 :  [24.5, 25.1, 26.3, 27.0, 25.8, 24.5, 25.1, 26.3, 27.0, 25.8]
NumPy x2 :  [49.  50.2 52.6 54.  51.6]


# Partie 2 : Création des données

In [7]:
# 1) 10 mesures de température initialisées à zéro
temp_zeros=np.zeros(10)

# 2) 10 valeurs égales à 1
temp_ones=np.ones(10)

# 3) 10 valeurs initialisées à 25
temp_25=np.full(10, 25)

# 4) Matrice identité 5x5
identite=np.eye(5)

# 5) Les 24 heures d'une journée (0 à 23)
heures=np.arange(24)

# 6) 10 valeurs régulièrement réparties entre 20°C et 30°C
temp_reparties=np.linspace(20, 30, 10)

# 7) 100 températures aléatoires reproductibles
rng=np.random.default_rng(seed=42)
temp_aleatoires=rng.normal(loc=25, scale=3, size=100).round(1)

print("Zéros : ", temp_zeros)
print("Uns : ", temp_ones)
print("25 :", temp_25)
print("Identité :\n", identite)
print("Heures :", heures)
print("Réparties 20-30 :", temp_reparties)
print("Aléatoires (extrait) :", temp_aleatoires[:10])

Zéros :  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Uns :  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
25 : [25 25 25 25 25 25 25 25 25 25]
Identité :
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Heures : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Réparties 20-30 : [20.         21.11111111 22.22222222 23.33333333 24.44444444 25.55555556
 26.66666667 27.77777778 28.88888889 30.        ]
Aléatoires (extrait) : [25.9 21.9 27.3 27.8 19.1 21.1 25.4 24.1 24.9 22.4]


# Partie 3 : Exploration des tableaux

In [8]:
# 1) 24 températures aléatoires d'une journée
rng=np.random.default_rng(seed=1)
temperatures_jour=rng.normal(loc=25, scale=3, size=24).round(1)

print("Températures: ", temperatures_jour)

# 2) Propriétés du tableau
print("a) Nombre de dimensions :", temperatures_jour.ndim)
print("b) Nombre de valeurs :", temperatures_jour.size)
print("c) Type des données :", temperatures_jour.dtype)
print("d) Forme du tableau :", temperatures_jour.shape)


Températures:  [26.  27.5 26.  21.1 27.7 26.3 23.4 26.7 26.1 25.9 25.1 26.6 22.8 24.5
 23.6 26.8 25.1 24.1 22.7 24.2 25.  24.2 28.9 28. ]
a) Nombre de dimensions : 1
b) Nombre de valeurs : 24
c) Type des données : float64
d) Forme du tableau : (24,)


# Partie 4 : Indexation et slicing

In [9]:
# 1) Première mesure
print("Première mesure :", temperatures_jour[0])

# 2) Dernière mesure
print("Dernière température :", temperatures_jour[-1])

# 3) Température de 8h
print("Température à 8h :", temperatures_jour[8])

# 4) Températures de 8h à 12h
print("Températures 8h-12h :", temperatures_jour[8:13])

# 5) Températures des 6 premières heures
print("6 premières heures :", temperatures_jour[:6])

# 6) Températures des heures paires
print("Heures paires :", temperatures_jour[::2])

Première mesure : 26.0
Dernière température : 28.0
Température à 8h : 26.1
Températures 8h-12h : [26.1 25.9 25.1 26.6 22.8]
6 premières heures : [26.  27.5 26.  21.1 27.7 26.3]
Heures paires : [26.  26.  27.7 23.4 26.1 25.1 22.8 23.6 25.1 22.7 25.  28.9]


# Partie 5 : Filtrage booléen

In [10]:
# 1) Températures supérieures à 30°C
print("Températures > 30°C :", temperatures_jour[temperatures_jour > 30])

# 2) Températures "normales" (entre 20°C et 30°C)
normales = temperatures_jour[(temperatures_jour >= 20) & (temperatures_jour <= 30)]
print("Températures normales (20-30°C) :", normales)

# 3) Tableau booléen des anomalies (> 35°C)
anomalies = temperatures_jour > 35
print("Anomalies (booléen) :", anomalies)

# 4) Nombre de températures anormales
print("Nombre d'anomalies :", anomalies.sum())

Températures > 30°C : []
Températures normales (20-30°C) : [26.  27.5 26.  21.1 27.7 26.3 23.4 26.7 26.1 25.9 25.1 26.6 22.8 24.5
 23.6 26.8 25.1 24.1 22.7 24.2 25.  24.2 28.9 28. ]
Anomalies (booléen) : [False False False False False False False False False False False False
 False False False False False False False False False False False False]
Nombre d'anomalies : 0


# Partie 6 : Manipulation des dimensions (5 capteurs)

In [11]:
# 1) Matrice des températures des 5 capteurs sur 24h
rng = np.random.default_rng(seed=2)
temp_5_capteurs = rng.normal(loc=25, scale=3, size=(5, 24)).round(1)
print("Matrice (5 capteurs x 24h) :\n", temp_5_capteurs)
print("Shape :", temp_5_capteurs.shape)

# 2) Transformation en tableau unidimensionnel
temp_flatten = temp_5_capteurs.flatten()
print("Aplati, shape :", temp_flatten.shape)

# 3) Transposée de la matrice
temp_transposee = temp_5_capteurs.T
print("Transposée, shape :", temp_transposee.shape)

# 4) Toutes les mesures du capteur 1
print("Capteur 1 :", temp_5_capteurs[0, :])

# 5) Toutes les mesures du capteur 5
print("Capteur 5 :", temp_5_capteurs[4, :])

# 6) Mesures de tous les capteurs à 10h
print("Tous les capteurs à 10h :", temp_5_capteurs[:, 10])

# 7) Mesures des capteurs 2 à 4 entre 8h et 12h
print("Capteurs 2-4, 8h-12h :\n", temp_5_capteurs[1:4, 8:13])


Matrice (5 capteurs x 24h) :
 [[25.6 23.4 23.8 17.7 30.4 28.4 24.  27.3 25.8 23.3 27.9 24.1 24.  22.6
  26.4 24.7 26.6 23.2 25.4 22.3 27.5 25.6 26.  26.2]
 [22.  27.3 31.2 20.1 19.8 20.5 27.5 25.4 28.2 27.2 25.6 25.9 24.5 27.6
  21.6 23.7 25.7 30.4 22.7 21.8 23.3 27.9 24.3 29. ]
 [19.4 28.4 28.1 20.7 25.5 28.6 25.3 28.  32.1 25.8 24.2 22.7 26.9 24.4
  24.5 24.7 26.9 21.8 20.4 17.7 28.6 25.2 29.5 25. ]
 [22.8 26.4 24.8 21.2 22.3 30.3 26.1 26.2 24.2 22.9 27.7 24.7 22.7 24.6
  22.3 25.6 28.4 22.5 29.3 23.  25.5 22.5 24.3 25.1]
 [23.7 22.9 23.  22.5 20.3 24.2 26.2 27.7 26.9 32.4 26.  23.6 30.6 21.9
  27.9 22.1 26.1 19.1 27.7 24.5 22.1 30.  27.3 25.1]]
Shape : (5, 24)
Aplati, shape : (120,)
Transposée, shape : (24, 5)
Capteur 1 : [25.6 23.4 23.8 17.7 30.4 28.4 24.  27.3 25.8 23.3 27.9 24.1 24.  22.6
 26.4 24.7 26.6 23.2 25.4 22.3 27.5 25.6 26.  26.2]
Capteur 5 : [23.7 22.9 23.  22.5 20.3 24.2 26.2 27.7 26.9 32.4 26.  23.6 30.6 21.9
 27.9 22.1 26.1 19.1 27.7 24.5 22.1 30.  27.3 25.1]
Tous le

# Partie 7 : Concaténation (2e bâtiment, 3 capteurs)

In [12]:
# 1) Matrice des températures des 3 capteurs du 2e bâtiment
rng = np.random.default_rng(seed=3)
temp_3_capteurs = rng.normal(loc=25, scale=3, size=(3, 24)).round(1)
print("Bâtiment 2 (3 capteurs x 24h) :\n", temp_3_capteurs)

# 2) Fusion des 8 capteurs (5 + 3), deux méthodes équivalentes
tous_capteurs_v1 = np.concatenate([temp_5_capteurs, temp_3_capteurs], axis=0)  # Méthode 1
tous_capteurs_v2 = np.vstack([temp_5_capteurs, temp_3_capteurs])               # Méthode 2

print("Dimensions après fusion (concatenate) :", tous_capteurs_v1.shape)
print("Dimensions après empilement (vstack) :", tous_capteurs_v2.shape)
print("Résultats identiques :", np.array_equal(tous_capteurs_v1, tous_capteurs_v2))


Bâtiment 2 (3 capteurs x 24h) :
 [[31.1 17.3 26.3 23.3 23.6 24.4 18.9 24.3 22.4 35.  25.7 23.9 24.2 23.
  21.8 23.8 26.4 24.3 27.9 24.4 25.1 29.6 26.6 23.5]
 [24.5 26.6 30.8 24.2 24.3 28.  22.3 24.1 27.6 26.7 25.3 27.  16.5 28.1
  22.1 20.  25.8 27.1 23.7 21.8 25.1 24.8 29.2 27.2]
 [25.6 28.3 24.4 22.2 26.8 26.7 24.4 22.7 25.7 17.5 27.1 26.5 20.1 25.2
  22.1 27.3 18.9 22.3 27.1 28.5 18.5 23.5 26.  23.2]]
Dimensions après fusion (concatenate) : (8, 24)
Dimensions après empilement (vstack) : (8, 24)
Résultats identiques : True


# Partie 8 : Calcul scientifique (24 températures du bâtiment 1)

In [13]:
# 1) Statistiques descriptives
print("Min :", temperatures_jour.min())
print("Max :", temperatures_jour.max())
print("Somme :", temperatures_jour.sum())
print("Moyenne :", temperatures_jour.mean().round(2))
print("Médiane :", np.median(temperatures_jour))
print("Variance :", temperatures_jour.var().round(2))
print("Écart-type :", temperatures_jour.std().round(2))

Min : 21.1
Max : 28.9
Somme : 608.3
Moyenne : 25.35
Médiane : 25.5
Variance : 3.4
Écart-type : 1.84


In [14]:
# 2) Standardisation : (x - moyenne) / écart-type
temp_standardisees = (temperatures_jour - temperatures_jour.mean()) / temperatures_jour.std()
print("Standardisées (extrait) :", temp_standardisees.round(2)[:6])
print("Moyenne après standardisation :", temp_standardisees.mean().round(6))
print("Écart-type après standardisation :", temp_standardisees.std().round(6))


Standardisées (extrait) : [ 0.35  1.17  0.35 -2.3   1.28  0.52]
Moyenne après standardisation : 0.0
Écart-type après standardisation : 1.0


In [15]:
# 3) Normalisation Min-Max : (x - min) / (max - min)
temp_normalisees = (temperatures_jour - temperatures_jour.min()) / (temperatures_jour.max() - temperatures_jour.min())
print("Normalisées (extrait) :", temp_normalisees.round(2)[:6])
print("Min après normalisation :", temp_normalisees.min())
print("Max après normalisation :", temp_normalisees.max())

Normalisées (extrait) : [0.63 0.82 0.63 0.   0.85 0.67]
Min après normalisation : 0.0
Max après normalisation : 1.0


In [16]:
# 4) Conversion en Fahrenheit : F = C * 9/5 + 32
temp_fahrenheit = temperatures_jour * 9/5 + 32
print("Températures en Fahrenheit :", temp_fahrenheit.round(1))

Températures en Fahrenheit : [78.8 81.5 78.8 70.  81.9 79.3 74.1 80.1 79.  78.6 77.2 79.9 73.  76.1
 74.5 80.2 77.2 75.4 72.9 75.6 77.  75.6 84.  82.4]


# Partie 9 : Broadcasting

In [17]:
# 1) Matrice des températures à 10h, 11h, 12h dans le 2e bâtiment (3 capteurs)
rng = np.random.default_rng(seed=4)
temperatures_3x3 = rng.normal(loc=25, scale=2, size=(3, 3)).round(1)
# lignes = 10h, 11h, 12h | colonnes = Capteur 1, Capteur 2, Capteur 3
print("Températures 10h/11h/12h (3 heures x 3 capteurs) :\n", temperatures_3x3)


Températures 10h/11h/12h (3 heures x 3 capteurs) :
 [[23.7 24.7 28.3]
 [26.3 21.7 25. ]
 [23.8 25.3 21.8]]


In [18]:
# 2) Correction de calibration par capteur, appliquée automatiquement (broadcasting)
correction = np.array([1, -0.5, 0.2])
mesures_corrigees = temperatures_3x3 + correction

print("Correction par capteur :", correction)
print("Mesures corrigées :\n", mesures_corrigees)

Correction par capteur : [ 1.  -0.5  0.2]
Mesures corrigées :
 [[24.7 24.2 28.5]
 [27.3 21.2 25.2]
 [24.8 24.8 22. ]]
